### ISSUE TITLE
Rails 4.2 support, please?

### ISSUE THREAD

**Issue by clarkewd** [Lucasosf/json_form_fields#7]
Can you update for Rails 4.2 please?

```
Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (4.2.0)

  In Gemfile:
    json_form_fields (~> 0.0.6) ruby depends on
      railties (~> 4.1.8) ruby
```

**Comment by lucasprag** [comment]
Sure :+1:

**Comment by lucasprag** [comment]
This is already available. Thanks =)

**Comment by clarkewd** [comment]
Thank you for updating this. 

Also, I'm wondering if maybe the `Gemfile.lock` should not be part of them repository - maybe check out: [Should Gemfile.lock be included in .gitignore?](http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore) which says:

> Depends on what you are working on. If you are working on a gem, then DO NOT check in your Gemfile.lock. If you are working on a Rails app, then DO check in your Gemfile.lock. 

So perhaps keeping the `Gemfile.lock` locally and removing it from the repository might prevent future issues like this one?

**Comment by lucasprag** [comment]
Awesome, I'll read this and I'll think about. Thanks for the tip. :+1:

**Comment by lucasprag** [comment]
Well done.
